Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Odev.Controllers
{
    public class AdminController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Odev.Models;
using Odev.ViewModels;

namespace Odev.Controllers
{
    public class CarController : Controller
    {
        private readonly AppDbContext _context;

        public CarController(AppDbContext appDbContext)
        {
            _context = appDbContext;
        }

        [Authorize]
        public IActionResult Index()
        {
            var carsModel = _context.Cars.Select(x => new CarModel()
            {
                Id = x.Id,
                Name = x.Name,
                Title = x.Title,
                Description=x.Description,
                Price=x.Price,
                Status = x.Status

            }).ToList();
            return View(carsModel);
        }
        public IActionResult Detail(int id)
        {
            var carModel = _context.Cars.Select(x => new CarModel()
            {
                Id = x.Id,
                Name = x.Name,
                Title = x.Title,
                Description =x.Description, 
                Price = x.Price,
                Status = x.Status

            }).SingleOrDefault(x => x.Id == id);
            return View(carModel);

        }
        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(CarModel model)
        {
            var car = new Car();
            car.Name = model.Name;
            car.Title = model.Title;
            car.Description = model.Description;
            car.Price = model.Price;
            car.Status = model.Status;

            _context.Cars.Add(car);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var carModel = _context.Cars.Select(x => new CarModel()
            {
                Id = x.Id,
                Name = x.Name,
                Title = x.Title,
                Description = x.Description,
                
                Price = x.Price,
                Status = x.Status

            }).SingleOrDefault(x => x.Id == id);
            return View(carModel);
        }

        [HttpPost]
        public IActionResult Edit(CarModel model)
        {
            var car = _context.Cars.SingleOrDefault(x => x.Id == model.Id);
            car.Name = model.Name;
            car.Title = model.Title;
            car.Description = model.Description;   
            car.Price = model.Price;
            car.Status = model.Status;

            _context.Cars.Update(car);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var carModel = _context.Cars.Select(x => new CarModel()
            {
                Id = x.Id,
                Name = x.Name,
                Title = x.Title,
                Description = x.Description,
                Price = x.Price,
                Status = x.Status

            }).SingleOrDefault(x => x.Id == id);
            return View(carModel);
        }

        [HttpPost]
        public IActionResult Delete(CarModel model)
        {
            var car = _context.Cars.SingleOrDefault(x => x.Id == model.Id);
            _context.Cars.Remove(car);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult ChangeStatus(int id, bool st)
        {
            var car = _context.Cars.SingleOrDefault(x => x.Id == id);
            car.Status = st;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Araç Kiralama</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Odev.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Araç Kiralama</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Araç Ekle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Odev - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>